server:
  port: 8050

spring:
  datasource:
    batch:
      url: jdbc-path
      username: dummyuser
      password: dummypass
      driver-class-name: @driver-class@
    app:
      url: jdbc-path
      username: dummyuser
      password: dummypass
      driver-class-name: @driver-class@
  sleuth:
    enabled: true
  #  output:
  #    ansi:
  #      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        type: INFO
  #  config:
  #    use-legacy-processing: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
  file:
    name: logs/dev_app.log
  org:
    thymeleaf: DEBUG