server:
  port: 8060

spring:
  datasource:
    #app:
    # url: jdbc-path
    # username: dummy-user
    # password: dummy-pass
    # driver-class-name: dummy-driver
    #test:
    # url: jdbc-path
    # username: dummy-user
    # password: dummy-pass
    # driver-class-name: dummy-driver
    app:
      url: jdbc:mariadb://bl-nas:3307/media_db
      username: nas_db_user
      password: BL-db.112358
      driver-class-name: org.mariadb.jdbc.Driver
    test:
      url: jdbc:mariadb://selmankaya.com:3306/selmank1_test_db
      username: selmank1_app
      password: NM$8pS3o2lR7
      driver-class-name: org.mariadb.jdbc.Driver
  sleuth:
    enabled: true
  #  output:
  #    ansi:
  #      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        type: INFO
  #  config:
  #    use-legacy-processing: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate: INFO
  file:
    name: logs/dev_app.log
  org:
    thymeleaf: DEBUG